version: "3"

services: 
    mongodb:
        container_name: notesdb
        image: mongo
        ports:
            - "27017:27017"
        volumes: 
            - ./dbData:/data/db
        environment: 
            MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
            MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"        

     